### ISSUE TITLE
Using multidimensional chebyshev_nodes 

### ISSUE THREAD

**Issue by CharlesRSmith44** [RJDennis/ChebyshevApprox.jl#35]
Hi,

Is it possible to use multidimensional chebyshev_nodes where the whole x,y domain is not feasible. For example, consider a problem with a two dimensional domain, x,y in [0,1]x[0,1], where points where  x+y >1 are infeasible. Is there a way to implement this directly? 

If not, the only real challenge is computing chebyshev_weights while implementing such a problem. If I am trying to approximate some function z = f(x,y) and set z = NaN for nodes where x+y > 0.  If I then try to evaluate chebyshev_weights(z,nodes,order,domain) the weights are all NaNs. 

Thank you for this package it is very useful.

**Comment by RJDennis** [comment]
I don't have a way of doing this within the package itself, which assumes that the domain is some hyper-rectangle that gets normalised to a hyper-cube.  If you have a function that transforms from a square to a triangle, then something could possibly be done, but I don't know what that function is.

**Comment by CharlesRSmith44** [comment]
What would that function look like?

**Comment by RJDennis** [comment]
All of the functions I have provided in the package assume that the approximation grid is a hyper-rectangle.  I sounds like what you need is some way of transforming back-and-forth between a hyper-cube and a hyper-triangle.  I don't know what that transformation is so I'm not sure I can help you.
